---

name: Create GitHubNext diagram
# yamllint disable-line rule:truthy
on:
  workflow_dispatch: {}
#  push:
#    branches: [ master, main ]

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "LICENSE,.github,.gitignore,.gitattributes,Docker"
